//
//  Langs.swift
//  Translator
//
//  Created by Jeremy Conley on 2/18/17.
//  Copyright © 2017 JeremyConley. All rights reserved.
//

import Foundation

struct Langs {

let langDic: Dictionary = ["Afrikaans" : "af",
                           "Albanian" : "sq",
                           "Anglo-Norman" : "xno",
                           "Arabic" : "ar",
                           "Aragonese" : "an",
                           "Armenian" : "hy",
                           "Asturian" : "ast",
                           "Azerbaijani" : "az",
                           "Basque" : "eu",
                           "Bavarian" : "bar",
                           "Belarusian" : "be",
                           "Bengali" : "bn",
                           "Bosnian" : "bs",
                           "Breton" : "br",
                           "Bulgarian" : "bg",
                           "Burmese" : "my",
                           "Catalan" : "ca",
                           "Chinese" : "zh",
                           "Coastal Swahili" : "swh",
                           "Crimean Turkish" : "crh",
                           "Croatian" : "hr",
                           "Czech" : "cs",
                           "Danish" : "da",
                           "Dutch" : "nl",
                           "English" : "en",
                           "Esperanto" : "eo",
                           "Estonian" : "et",
                           "Faroese" : "fo",
                           "Filipino" : "fil",
                           "Finnish" : "fi",
                           "French" : "fr",
                           "Galician" : "gl",
                           "Georgian" : "ka",
                           "German" : "de",
                           "Greek" : "el",
                           "Gujarati" : "gu",
                           "Haitian" : "ht",
                           "Hawaiian" : "haw",
                           "Hebrew" : "he",
                           "Hiligaynon" : "hil",
                           "Hindi" : "hi",
                           "Hungarian" : "hu",
                           "Icelandic" : "is",
                           "Ido" : "io",
                           "Indonesian" : "id",
                           "Interlingua" : "ia",
                           "Iranian Persian" : "pes",
                           "Irish" : "ga",
                           "Italian" : "it",
                           "Japanese" : "ja",
                           "Karachay-Balkar" : "krc",
                           "Kazakh" : "kk",
                           "Khasi" : "kha",
                           "Khmer" : "km",
                           "Korean" : "ko",
                           "Koyraboro Senni" : "ses",
                           "Kurdish" : "ku",
                           "Lao" : "lo",
                           "Latin" : "la",
                           "Latvian" : "lv",
                           "Limburgish" : "li",
                           "Lithuanian" : "lt",
                           "Low German" : "nds",
                           "Luxembourgish" : "lb",
                           "Macedonian" : "mk",
                           "Malay" : "ms",
                           "Malayalam" : "ml",
                           "Maltese" : "mt",
                           "Mandarin" : "cmn",
                           "Manx" : "gv",
                           "Marathi" : "mr",
                           "Middle French (ca. 1400-1600)" : "frm",
                           "Min Nan Chinese" : "nan",
                           "Mongolian" : "mn",
                           "Navajo" : "nav",
                           "Neapolitan" : "nap",
                           "Northern Sami" : "se",
                           "Norwegian" : "nb",
                           "Novial" : "nov",
                           "Occitan" : "oc",
                           "Old English" : "ang",
                           "Old French (842-ca. 1400)" : "fro",
                           "Old Norse" : "non",
                           "Papiamento" : "pap",
                           "Persian" : "fa",
                           "Piemontese" : "pms",
                           "Polish" : "pl",
                           "Portuguese" : "pt",
                           "Romanian" : "ro",
                           "Romansh" : "rm",
                           "Romany" : "rom",
                           "Russian" : "ru",
                           "Sanskrit" : "sa",
                           "Scots" : "sco",
                           "Scottish Gaelic" : "gd",
                           "Serbian" : "sr",
                           "Serbo Croatian" : "sh",
                           "Sicilian" : "scn",
                           "Slovak" : "sk",
                           "Slovenian" : "sl",
                           "South Azerbaijani" : "azb",
                           "Spanish" : "es",
                           "Standard Arabic" : "arb",
                           "Swahili" : "sw",
                           "Swedish" : "sv",
                           "Tagalog" : "tl",
                           "Tajik" : "tg",
                           "Tamil" : "ta",
                           "Tatar" : "tt",
                           "Telugu" : "te",
                           "Thai" : "th",
                           "Turkish" : "tr",
                           "Turkmen" : "tk",
                           "Ukrainian" : "uk",
                           "Urdu" : "ur",
                           "Uzbek" : "uz",
                           "Venetian" : "vec",
                           "Vietnamese" : "vi",
                           "Volapük" : "vo",
                           "Welsh" : "cy",
                           "Western Frisian" : "fy",
                           "Wymysorys" : "wym",
                           "Yiddish" : "yi",
                           "Yoruba" : "yo",
                           "Yucateco" : "yua",
                           "Zulu" : "zu"]
}
